language: java
dist: trusty
matrix:
  include:
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8

    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9

    - env: JDK='Oracle JDK 10'
      jdk: oraclejdk10

services: mysql

before_script:
# Import Database
  - mysql -e 'CREATE DATABASE test;'
  - mysql test < voj.sql

before_install:
# Download JDK installer
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
# Fix path error on JNI headers
  - sudo ln -nsf $JAVA_HOME/include/linux/jni_md.h $JAVA_HOME/include/jni_md.h
  - sudo ln -nsf $JAVA_HOME/include/linux/jawt_md.h $JAVA_HOME/include/jawt_md.h
# Setup test environment for Linux
  - cp judger/src/test/resources/voj-test-linux.properties judger/src/test/resources/voj-test.properties
# Find Maven Installation Path for root user
  - sudo find / -name mvn
  - export MVN_EXEC=`sudo find / -name mvn`
# Setup Maven for Oracle JDK 9
  - export MAVEN_SKIP_RC=true

script: 
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - mvn test -f web/pom.xml
  - sudo $MVN_EXEC test -f judger/pom.xml

after_script:
  - mysql -e 'DROP DATABASE test;'

after_success:
  - mvn -f web/pom.xml cobertura:cobertura coveralls:report
  - mvn -f judger/pom.xml cobertura:cobertura coveralls:reportTABASE test;'

after_success:
  - mvn -f web/pom.xml cobertura:cobertura coveralls:report
  - mvn -f judger/pom.xml cobertura:cobertura coveralls:report