language: java
dist: trusty
env:
  - JDK=oraclejdk8
  - JDK=oraclejdk9

matrix:
  allow_failures:
    - JDK: oraclejdk9

services: mysql

before_script:
# Switch JDK
  - jdk_switcher use $JDK
# Import Database
  - mysql -e 'CREATE DATABASE test;'
  - mysql test < voj.sql

before_install:
# Fix path error on JNI headers
  - sudo ln -nsf $JAVA_HOME/include/linux/jni_md.h $JAVA_HOME/include/jni_md.h
  - sudo ln -nsf $JAVA_HOME/include/linux/jawt_md.h $JAVA_HOME/include/jawt_md.h
# Setup test environment for Linux
  - cp judger/src/test/resources/voj-test-linux.properties judger/src/test/resources/voj-test.properties
# Setup Maven for Oracle JDK 9
  - export MAVEN_SKIP_RC=true

script: 
  - mvn test -f web/pom.xml
  - mvn test -f judger/pom.xml

after_script:
  - mysql -e 'DROP DATABASE test;'

after_success:
  - mvn -f web/pom.xml cobertura:cobertura coveralls:report
  - mvn -f judger/pom.xml cobertura:cobertura coveralls:reportTABASE test;'

after_success:
  - mvn -f web/pom.xml cobertura:cobertura coveralls:report
  - mvn -f judger/pom.xml cobertura:cobertura coveralls:report